liip_imagine:
    driver: "gd"  # ou "imagick" si installé, meilleur rendu

    resolvers:
        default:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: /media/cache

    filter_sets:
        cache: ~  # nécessaire
        thumbnail_realisation:
            quality: 85
            filters:
                thumbnail:
                    size: [1024, 768]  # largeur x hauteur
                    mode: outbound    # crop pour remplir exactement la taille

        thumbnail_realisation_detail:
            quality: 85
            filters:
                thumbnail:
                    size: [ 1024, 683 ]  # largeur x hauteur
                    mode: outbound    # crop pour remplir exactement la taille

        thumbnail_article:
            quality: 85
            filters:
                thumbnail:
                    size: [ 1024, 683 ]  # largeur x hauteur
                    mode: outbound    # crop pour remplir exactement la taille


