vich_uploader:
    db_driver: orm

    mappings:
        articleImage:
            uri_prefix: upload/images/articles
            upload_destination: '%kernel.project_dir%/public/upload/images/articles'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        realisationPoster:
            uri_prefix: upload/images/realisations
            upload_destination: '%kernel.project_dir%/public/upload/images/realisations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        realisationImage:
            uri_prefix: upload/images/realisations
            upload_destination: '%kernel.project_dir%/public/upload/images/realisations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
